Highcharts.chart("container", {
  title: {
    text: "Flights Where are they coming from",
  },

  accessibility: {
    point: {
      valueDescriptionFormat:
        "{index}. From {point.from} to {point.to}: {point.weight}.",
    },
  },

  series: [
    {
      keys: ["from", "to", "weight"],
      data: [
        ["SFO", "LAX", 13744],
        ["JFK", "LAX", 12016],
        ["LAS", "LAX", 9715],
        ["ORD", "LAX", 7941],
        ["SEA", "LAX", 7765],
        ["PHX", "LAX", 7380],
        ["DFW", "LAX", 6634],
        ["SJC", "LAX", 6339],
        ["OAK", "LAX", 6281],
        ["DEN", "LAX", 5688],
        ["ATL", "LAX", 5669],
        ["SMF", "LAX", 5574],
        ["SLC", "LAX", 5549],
        ["HNL", "LAX", 5244],
        ["SAN", "LAX", 4619],
        ["EWR", "LAX", 4603],
        ["IAH", "LAX", 4432],
        ["BOS", "LAX", 4055],
        ["IAD", "LAX", 3606],
        ["PDX", "LAX", 3279],
        ["MSP", "LAX", 3093],
        ["MIA", "LAX", 3024],
        ["OGG", "LAX", 2711],
        ["TUS", "LAX", 2633],
        ["AUS", "LAX", 2597],
        ["DAL", "LAX", 2473],
        ["MCO", "LAX", 2414],
        ["DTW", "LAX", 2003],
        ["CLT", "LAX", 1958],
        ["RNO", "LAX", 1901],
        ["PHL", "LAX", 1886],
        ["MDW", "LAX", 1858],
        ["MSY", "LAX", 1850],
        ["ABQ", "LAX", 1834],
        ["FLL", "LAX", 1752],
        ["FAT", "LAX", 1693],
        ["BNA", "LAX", 1637],
        ["SAT", "LAX", 1556],
        ["HOU", "LAX", 1540],
        ["MRY", "LAX", 1529],
        ["SBA", "LAX", 1460],
        ["STL", "LAX", 1458],
        ["KOA", "LAX", 1385],
        ["SBP", "LAX", 1373],
        ["LIH", "LAX", 1304],
        ["BWI", "LAX", 1115],
        ["DCA", "LAX", 1000],
        ["MCI", "LAX", 981],
        ["ELP", "LAX", 916],
        ["CLE", "LAX", 804],
        ["RDU", "LAX", 803],
        ["IND", "LAX", 785],
        ["ASE", "LAX", 774],
        ["PSP", "LAX", 729],
        ["BOI", "LAX", 682],
        ["COS", "LAX", 644],
        ["CLD", "LAX", 641],
        ["TPA", "LAX", 603],
        ["CMH", "LAX", 588],
        ["CVG", "LAX", 533],
        ["EUG", "LAX", 513],
        ["ANC", "LAX", 382],
        ["MKE", "LAX", 380],
        ["OKC", "LAX", 316],
        ["ITO", "LAX", 261],
        ["MEM", "LAX", 257],
        ["JAC", "LAX", 256],
        ["PIT", "LAX", 255],
        ["SMX", "LAX", 249],
        ["RDM", "LAX", 240],
        ["SAF", "LAX", 230],
        ["GEG", "LAX", 159],
        ["BZN", "LAX", 143],
        ["EGE", "LAX", 110],
        ["PBI", "LAX", 77],
        ["HDN", "LAX", 63],
        ["OMA", "LAX", 63],
        ["ICT", "LAX", 58],
        ["MTJ", "LAX", 29],
        ["MSN", "LAX", 1],
        ["CID", "LAX", 1],
      ],
      type: "dependencywheel",
      name: "Flights - Origin to Destination",
      dataLabels: {
        color: "#333",
        textPath: {
          enabled: true,
          attributes: {
            dy: 5,
            rotation: 90,
          },
        },
        distance: 15,
      },
      size: "95%",
    },
  ],
});
